### PR TITLE
Use $size instead of counting on each iteration in QuickSort

### PR DESCRIPTION
**Pull request by berezuev**
## Description
Use $size instead of counting on each iteration in QuickSort

### CODE REVIEW

**Comment by doganoo** [comment]
Hey

thank you for this PR.
Could you please add a author tag to each files header that you have changed?

like this:

> @author Copyright (c) year, Firstname Lastname <mail [at] example.com>

Thank you for contributing to PHPAlgorithms 😊

**Review by doganoo — CHANGES_REQUESTED** [review]
Hey

thank you for this PR.
Could you please add a author tag to each files header that you have changed?

like this:

> @author Firstname Lastname \<mail [at] example.com\>

Thank you for contributing to PHPAlgorithms 😊

**Comment by berezuev** [comment]
@doganoo haha! Such author, many changes :laughing:

**Review by doganoo — APPROVED** [review]

**Comment by doganoo** [comment]
hehe, yeah I was looking for the right format 🙈

Thank you for this PR. It will be going live with the next release (probably 1.0.0) 😊

**Pull request merged**
